multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /tmp/mimir
  # replication_factor moved to ingester to avoid common error

ingester:
  ring:
    instance_id: "mimir-1"
    kvstore:
      store: inmemory
    replication_factor: 1

blocks_storage:
  storage_prefix: blocks
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/blocks

compactor:
  data_dir: /tmp/mimir/compactor

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/alerts
