global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: http://mimir:9009/api/v1/push

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:9464']

  - job_name: 'post-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['post-service:9464']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
